name: cicd

on:
    push:
        branches: ["main"]

jobs:
    build_test_backend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup nodejs
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - name: Run backend tests
              working-directory: backend
              run: npm test

            - name: Build the backend docker image
              working-directory: backend
              run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    build_frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup nodejs
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install frontend dependencies
              working-directory: frontend
              run: npm ci

            - name: Run frontend tests
              working-directory: frontend
              run: npm test -- --watchAll=false

            - name: Build the frontend Docker image
              working-directory: frontend
              run: docker build . --file Dockerfile --tag my-frontend-image-name:$(date +%s)
